project:
  type: website

website:
  title: "IS415-GAA"
  navbar:
    left:
      - href: index.qmd
        text: Week 1
      - href: Week2.qmd
        text: Week 2
      - href: Week3.qmd
        text: Week 3

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

