project:
  type: website

website:
  title: "IS415-GAA"
  navbar:
    background: "#A75D5D"
    left:
      - href: index.qmd
        text: "Home"
        
      - text: "In-Class Exercise"
        menu: 
          - text: "Week 1"
            href: ICE/Week 1/Week1.qmd
          - text: "Week 2"
            href: ICE/Week 2/Week2.qmd
          - text: "Week 3"
            href: ICE/Week 3/Week3.qmd
          - text: "Week 4"
            href: ICE/Week 4/Week4.qmd
            
            
      - text: "Hands-on Exercise"
        menu: 
          - text: "Week 1"
            href: Hands-on/Week 1/Week1.qmd
          - text: "Week 2"
            href: Hands-on/Week 2/Week2.qmd
          - text: "Week 3"
            href: Hands-on/Week 3/Week3.qmd
          - text: "Week 4"
            href: Hands-on/Week 4/Week4.qmd
            
            
      - text: "Take-home Exercise"
        menu: 
          - text: "Exercise 1"
            href: Take-home/Ex1/Ex1.qmd
          

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

